name: Yoast e2e tests

on:
  push:
    branches:
      - integrate/e2e-tests-to-ci

jobs:
  e2e-tests:
    name: e2e-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS version
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup PHP with composer v2 
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          tools: composer:v2

      - name: Install gettext (includes msgcat)
        run: |
          sudo apt-get -y install gettext

      - name: Install composer dependencies
        run: |
          composer update
          composer install

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn

      - name: Build the plugin
        run: |
          grunt build

      - name: Install WordPress
        run: |
          chmod -R 767 ./
          yarn wp-env start

      - name: Install and activate the yoast-simple-custom-post-type plugin
        run: |
          yarn wp-env run tests-cli wp plugin install "https://github.com/Yoast/wordpress-seo/blob/trunk/packages/e2e-tests/data/yoast-simple-custom-post-type.zip?raw=true"
          yarn wp-env run tests-cli wp plugin activate yoast-simple-custom-post-type

      - name: Run the e2e tests
        run: |
          cd packages/e2e-tests
          yarn test:e2e          
